import { useState } from 'react'
import { Eye, EyeOff, ShieldPlus } from 'lucide-react'
import { api, errorMessage } from '../services/api'

function CreateUserForm({ onUserCreated }) {
  const [formData, setFormData] = useState({ name: '', email: '', password: '', role: 'User' })
  const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [showPassword, setShowPassword] = useState(false)
  const score = [formData.password.length >= 10, /[A-Z]/.test(formData.password), /[a-z]/.test(formData.password), /\d/.test(formData.password), /[^A-Za-z0-9]/.test(formData.password)].filter(Boolean).length
  const submit = async (event) => { event.preventDefault(); setLoading(true); setError(''); setSuccess(''); try { const result = await api.post('/users', formData); setSuccess(`${result.data.user.name} was added with key ${result.data.user.user_id}.`); setFormData({ name: '', email: '', password: '', role: 'User' }); onUserCreated() } catch (err) { setError(errorMessage(err)) } finally { setLoading(false) } }
  const change = event => setFormData({ ...formData, [event.target.name]: event.target.value })
  return <form onSubmit={submit} className="user-form">{error && <div className="alert alert-error" role="alert">{error}</div>}{success && <div className="alert alert-success" role="status">{success}</div>}<label className="form-group">Full name<input name="name" value={formData.name} onChange={change} className="form-control" placeholder="e.g. Priya Sharma" required /></label><label className="form-group">Work email<input name="email" type="email" value={formData.email} onChange={change} className="form-control" placeholder="priya@institute.edu" required /></label><label className="form-group">Access role<select name="role" value={formData.role} onChange={change} className="form-control"><option value="User">Standard user</option><option value="Security Analyst">Security analyst</option><option value="Administrator">Administrator</option></select></label><label className="form-group">Temporary password<div className="password-field"><input name="password" type={showPassword ? 'text' : 'password'} value={formData.password} onChange={change} className="form-control" placeholder="Create a strong password" required /><button type="button" onClick={() => setShowPassword(!showPassword)} aria-label="Show or hide password">{showPassword ? <EyeOff size={17} /> : <Eye size={17} />}</button></div></label><div className="password-meter"><div className="meter-track"><i className={`meter-fill score-${score}`} /></div><span>{score < 3 ? 'Needs strengthening' : score < 5 ? 'Good password' : 'Strong password'}</span></div><button type="submit" className="btn btn-wide" disabled={loading}>{loading ? 'Creating account…' : <><ShieldPlus size={17} /> Create secure account</>}</button></form>
}
export default CreateUserForm
